// Generated by SpecForge — do not edit manually
// Authentication middleware (jwt)

import type { FastifyRequest, FastifyReply } from "fastify";

export interface AuthUser {
  id: string;
  role: "public" | "authenticated" | "admin" | "owner";
}

declare module "fastify" {
  interface FastifyRequest {
    user?: AuthUser;
  }
}

/**
 * JWT authentication guard.
 * Verifies the Authorization header and attaches user to request.
 */
export async function authGuard(
  request: FastifyRequest,
  reply: FastifyReply
): Promise<void> {
  const authHeader = request.headers.authorization;

  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    reply.status(401).send({
      error: "Unauthorized",
      message: "Missing or invalid Authorization header",
    });
    return;
  }

  const token = authHeader.substring(7);

  try {
    // TODO: Implement actual jwt token verification
    // const payload = await verifyToken(token);
    const payload = { id: "user-id", role: "authenticated" as const };

    request.user = {
      id: payload.id,
      role: payload.role,
    };
  } catch (err) {
    reply.status(401).send({
      error: "Unauthorized",
      message: "Invalid or expired token",
    });
  }
}

/**
 * Role-based access control middleware.
 * Checks if the authenticated user has the required role.
 */
export function requireRole(...roles: AuthUser["role"][]) {
  return async (request: FastifyRequest, reply: FastifyReply): Promise<void> => {
    if (!request.user) {
      reply.status(401).send({
        error: "Unauthorized",
        message: "Authentication required",
      });
      return;
    }

    if (!roles.includes(request.user.role)) {
      reply.status(403).send({
        error: "Forbidden",
        message: `Requires one of: ${roles.join(", ")}`,
      });
    }
  };
}

/**
 * Owner-only access control.
 * Checks if the authenticated user owns the resource.
 */
export function requireOwner(getOwnerId: (request: FastifyRequest) => string | Promise<string>) {
  return async (request: FastifyRequest, reply: FastifyReply): Promise<void> => {
    if (!request.user) {
      reply.status(401).send({
        error: "Unauthorized",
        message: "Authentication required",
      });
      return;
    }

    if (request.user.role === "admin") return;

    const ownerId = await getOwnerId(request);
    if (request.user.id !== ownerId) {
      reply.status(403).send({
        error: "Forbidden",
        message: "You do not own this resource",
      });
    }
  };
}
