// Generated by SpecForge — do not edit manually
// Global error handler middleware

import type { FastifyError, FastifyRequest, FastifyReply } from "fastify";

export interface ErrorResponse {
  error: string;
  message: string;
  statusCode: number;
  details?: unknown;
}

/**
 * Global error handler for Fastify.
 * Normalizes all errors into a consistent JSON response format.
 */
export function errorHandler(
  error: FastifyError,
  request: FastifyRequest,
  reply: FastifyReply
): void {
  const statusCode = error.statusCode ?? 500;

  const response: ErrorResponse = {
    error: getErrorName(statusCode),
    message: statusCode >= 500 ? "Internal Server Error" : error.message,
    statusCode,
  };

  // Include validation details for 400 errors
  if (statusCode === 400 && error.validation) {
    response.details = error.validation;
  }

  // Log server errors
  if (statusCode >= 500) {
    request.log.error(error);
  }

  reply.status(statusCode).send(response);
}

function getErrorName(statusCode: number): string {
  const names: Record<number, string> = {
    400: "Bad Request",
    401: "Unauthorized",
    403: "Forbidden",
    404: "Not Found",
    409: "Conflict",
    422: "Unprocessable Entity",
    429: "Too Many Requests",
    500: "Internal Server Error",
    502: "Bad Gateway",
    503: "Service Unavailable",
  };
  return names[statusCode] ?? "Error";
}

/**
 * Not found handler for unmatched routes.
 */
export function notFoundHandler(
  request: FastifyRequest,
  reply: FastifyReply
): void {
  reply.status(404).send({
    error: "Not Found",
    message: `Route ${request.method} ${request.url} not found`,
    statusCode: 404,
  });
}
