// Generated by SpecForge — do not edit manually
// Request validation middleware

import type { FastifyRequest, FastifyReply } from "fastify";

export interface ValidationError {
  field: string;
  message: string;
}

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
}

/**
 * Validate request body against a schema definition.
 */
export function validateBody(schema: Record<string, FieldValidator>) {
  return async (request: FastifyRequest, reply: FastifyReply): Promise<void> => {
    const body = request.body as Record<string, unknown> | undefined;
    if (!body || typeof body !== "object") {
      reply.status(400).send({
        error: "Bad Request",
        message: "Request body is required",
      });
      return;
    }

    const errors: ValidationError[] = [];

    for (const [field, validator] of Object.entries(schema)) {
      const value = body[field];

      if (validator.required && (value === undefined || value === null)) {
        errors.push({ field, message: `${field} is required` });
        continue;
      }

      if (value === undefined || value === null) continue;

      if (validator.type === "string" && typeof value !== "string") {
        errors.push({ field, message: `${field} must be a string` });
      }

      if (validator.type === "number" && typeof value !== "number") {
        errors.push({ field, message: `${field} must be a number` });
      }

      if (validator.type === "boolean" && typeof value !== "boolean") {
        errors.push({ field, message: `${field} must be a boolean` });
      }

      if (validator.min !== undefined && typeof value === "number" && value < validator.min) {
        errors.push({ field, message: `${field} must be at least ${validator.min}` });
      }

      if (validator.max !== undefined && typeof value === "number" && value > validator.max) {
        errors.push({ field, message: `${field} must be at most ${validator.max}` });
      }

      if (validator.values && typeof value === "string" && !validator.values.includes(value)) {
        errors.push({ field, message: `${field} must be one of: ${validator.values.join(", ")}` });
      }
    }

    if (errors.length > 0) {
      reply.status(400).send({
        error: "Validation Error",
        message: "Request body validation failed",
        details: errors,
      });
    }
  };
}

export interface FieldValidator {
  type: "string" | "number" | "boolean" | "object";
  required?: boolean;
  min?: number;
  max?: number;
  values?: string[];
}

/**
 * Validate request params contain a valid UUID id.
 */
export async function validateIdParam(
  request: FastifyRequest,
  reply: FastifyReply
): Promise<void> {
  const params = request.params as Record<string, string>;
  const id = params.id;

  if (!id) {
    reply.status(400).send({
      error: "Bad Request",
      message: "ID parameter is required",
    });
    return;
  }

  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!uuidRegex.test(id)) {
    reply.status(400).send({
      error: "Bad Request",
      message: "ID must be a valid UUID",
    });
  }
}
