import * as fs from "node:fs";
import * as path from "node:path";
import { execSync } from "node:child_process";
import { loadConfig } from "@specforge/core/config";
import { resolveSpecDir } from "@specforge/core/sequence";
import { getGitContext } from "@specforge/core/git";
import { parseTasksMarkdown } from "@specforge/core/tasks";

export interface IssuesCommandOptions {
  dryRun?: boolean;
}

export async function issuesCommand(
  specId: string,
  opts: IssuesCommandOptions = {}
): Promise<void> {
  if (!specId) {
    console.error(
      "\n  Please provide a spec ID.\n  Usage: specforge issues <spec-id>\n"
    );
    process.exit(1);
  }

  const config = loadConfig();
  const specsDir = path.resolve(config.specsDir);
  const specDir = resolveSpecDir(specsDir, specId);

  if (!specDir) {
    console.error(`\n  Spec not found: ${specId}`);
    process.exit(1);
  }

  const tasksPath = path.join(specDir, "tasks.md");
  if (!fs.existsSync(tasksPath)) {
    console.error(`\n  No tasks.md found in: ${specDir}`);
    console.error(`  Run 'specforge tasks ${specId}' first.\n`);
    process.exit(1);
  }

  // Verify git and gh CLI
  const gitContext = getGitContext();
  if (!gitContext.isRepo) {
    console.error("\n  Not inside a git repository.\n");
    process.exit(1);
  }

  if (!gitContext.remoteUrl) {
    console.error("\n  No git remote configured. Push to GitHub first.\n");
    process.exit(1);
  }

  // Check gh CLI availability
  if (!opts.dryRun) {
    try {
      execSync("gh --version", { stdio: "pipe" });
    } catch {
      console.error(
        "\n  GitHub CLI (gh) not found. Install it: https://cli.github.com/\n"
      );
      process.exit(1);
    }
  }

  // Parse tasks
  const content = fs.readFileSync(tasksPath, "utf-8");
  const taskPhases = parseTasksMarkdown(content);
  const allTasks = taskPhases.flatMap((p) =>
    p.tasks.map((t) => ({ ...t, phase: p.name }))
  );

  const dirName = path.basename(specDir);
  console.log(`\n  Creating GitHub Issues for: ${dirName}\n`);

  if (opts.dryRun) {
    console.log("  [DRY RUN] Would create the following issues:\n");
  }

  const issueMap = new Map<string, number>();

  for (const task of allTasks) {
    if (task.done) {
      console.log(`  Skipping completed task: [${task.id}]`);
      continue;
    }

    const title = `[${task.id}] [${task.priority}] ${task.description}`;
    const labels = [
      `priority:${task.priority.toLowerCase()}`,
      `phase:${task.phase.toLowerCase().replace(/\s+/g, "-")}`,
    ];

    let body = `## Task from SpecForge\n\n`;
    body += `- **Task ID:** ${task.id}\n`;
    body += `- **Priority:** ${task.priority}\n`;
    body += `- **Phase:** ${task.phase}\n`;
    body += `- **Scenario:** ${task.scenarioRef}\n`;
    if (task.dependencies.length > 0) {
      body += `- **Dependencies:** ${task.dependencies.join(", ")}\n`;
    }
    body += `\n---\n_Generated by SpecForge from ${dirName}_\n`;

    if (opts.dryRun) {
      console.log(`  [${task.id}] ${title}`);
      if (task.dependencies.length > 0) {
        console.log(`    Dependencies: ${task.dependencies.join(", ")}`);
      }
    } else {
      try {
        const labelArgs = labels.map((l) => `--label "${l}"`).join(" ");
        const escapedTitle = title.replace(/"/g, '\\"');
        const escapedBody = body.replace(/"/g, '\\"');

        const result = execSync(
          `gh issue create --title "${escapedTitle}" --body "${escapedBody}" ${labelArgs} 2>&1 || true`,
          {
            cwd: process.cwd(),
            encoding: "utf-8",
            stdio: "pipe",
          }
        );

        // Extract issue number from URL
        const urlMatch = result.match(/\/issues\/(\d+)/);
        if (urlMatch) {
          const issueNum = parseInt(urlMatch[1], 10);
          issueMap.set(task.id, issueNum);
          console.log(`  Created: #${issueNum} — ${task.description}`);
        } else {
          console.log(`  Created issue for: [${task.id}] ${task.description}`);
        }
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.error(`  Failed to create issue for [${task.id}]: ${message}`);
      }
    }
  }

  // Summary
  const totalTasks = allTasks.filter((t) => !t.done).length;
  console.log(`\n  ${opts.dryRun ? "Would create" : "Created"} ${totalTasks} issues.`);

  if (!opts.dryRun && issueMap.size > 0) {
    console.log(
      `  Issue numbers: ${Array.from(issueMap.entries())
        .map(([taskId, num]) => `${taskId}=#${num}`)
        .join(", ")}`
    );
  }

  console.log();
}
