// Generated by SpecForge — do not edit manually
// Tests for User

import { describe, it, expect } from "vitest";

describe("User", () => {
  it("should create a user", async () => {
    // Action: create
    const input = {
  "email": "test@example.com",
  "name": "Test User"
};

    // TODO: Implement test — call the API endpoint
    // Expected status: 201
    const response = { status: 201, body: {} as Record<string, unknown> };

    expect(response.status).toBe(201);
    expect(response.body["email"]).toBe("test@example.com");
  });

  it("should reject invalid email", async () => {
    // Action: create
    const input = {
  "email": "not-an-email",
  "name": "Test"
};

    // TODO: Implement test — call the API endpoint
    // Expected status: 400
    const response = { status: 400, body: {} as Record<string, unknown> };

    expect(response.status).toBe(400);
  });

});
