import type { ParsedSpec, GeneratedFile, GenerateOptions, FieldSpec } from "@specforge-dev/core";
import { renderTemplate } from "../engine.js";
import type { SpecForgePlugin } from "../types.js";

function mapFieldToTsType(field: FieldSpec): string {
  switch (field.type) {
    case "uuid":
    case "string":
    case "text":
      return "string";
    case "integer":
    case "float":
      return "number";
    case "boolean":
      return "boolean";
    case "datetime":
    case "date":
      return "Date";
    case "json":
      return "Record<string, unknown>";
    case "enum":
      return (field.values ?? []).map((v) => `"${v}"`).join(" | ");
    case "relation":
      return "string"; // FK is stored as id string
    default:
      return "unknown";
  }
}

export const modelPlugin: SpecForgePlugin = {
  name: "model",
  version: "0.1.0",

  generate(spec: ParsedSpec, options: GenerateOptions): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    for (const [modelName, modelSpec] of Object.entries(spec.models)) {
      const fields: Record<string, Record<string, unknown>> = {};

      for (const [fieldName, fieldSpec] of Object.entries(modelSpec.fields)) {
        fields[fieldName] = {
          ...fieldSpec,
          tsType: mapFieldToTsType(fieldSpec),
          hasDefault: fieldSpec.default !== undefined,
        };
      }

      const content = renderTemplate("model/model.hbs", {
        modelName,
        fields,
      });

      files.push({
        path: `src/models/${modelName.toLowerCase()}.ts`,
        content: content.replace(/\n{3,}/g, "\n\n"),
        overwrite: true,
      });
    }

    // Generate index barrel file
    const indexLines = Object.keys(spec.models).map(
      (name) => `export * from "./${name.toLowerCase()}.js";`
    );
    files.push({
      path: "src/models/index.ts",
      content:
        "// Generated by SpecForge — do not edit manually\n\n" +
        indexLines.join("\n") +
        "\n",
      overwrite: true,
    });

    return files;
  },
};
