// Generated by SpecForge — do not edit manually
// Fastify server entry point

import Fastify from "fastify";
import userRoutes from "./routes/user.js";
import postRoutes from "./routes/post.js";
import customCommandRoutes from "./routes/customcommand.js";

const app = Fastify({
  logger: true,
});

// Register routes
app.register(userRoutes, { prefix: "/api/v1" });
app.register(postRoutes, { prefix: "/api/v1" });
app.register(customCommandRoutes, { prefix: "/api/v1" });

const start = async () => {
  try {
    await app.listen({ port: 3000, host: "0.0.0.0" });
    console.log("Server running at http://localhost:3000");
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();
